name: Test Lamina

on:
  schedule:
    - cron: "0 16/4 * * *"
  workflow_dispatch:

permissions:
  actions: read
  issues: write

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - run: cargo run
      - run: cargo test > log.log

      - name: Upload test log
        id: upload_log
        uses: actions/upload-artifact@v4
        with:
          name: test_log
          path: log.log
          retention-days: 1

      - name: Make issue body
        run: |
          echo "# $(date +'%Y-%m-%d %H:%M:%S')" 测试 > issue_body.md
          echo "下载日志：[${{ steps.upload_log.outputs.artifact-url }}](${{ steps.upload_log.outputs.artifact-url }})" >> issue_body.md
          echo "" >> issue_body.md
          echo '```' >> issue_body.md
          cat log.log >> issue_body.md
          echo '```' >> issue_body.md

      - name: Create a comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 1
          comment-id: 3192037735
          body-path: issue_body.md
          edit-mode: replace
