name: Test Lamina

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"
  workflow_dispatch:

permissions:
  actions: read
  issues: write

jobs:
  test:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - run: rustup update
      # - run: rustup component add llvm-tools-preview
      # - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - run: cargo run
      # - run: cargo llvm-cov run
      - run: cargo nextest run --profile=ci --test print_object
      # - run: cargo llvm-cov nextest --profile=ci --test print_object
      # - run: cargo llvm-cov report --lcov --output-path ./target/nextest/ci/lcov.info
      #   if: ${{ !cancelled() }}

      - uses: test-summary/action@v2
        if: ${{ !cancelled() }}
        with:
          paths: target/nextest/ci/junit.xml
          output: target/nextest/ci/summary.md

      - uses: actions/upload-artifact@v4
        id: upload_artifact
        if: ${{ !cancelled() }}
        with:
          name: artifact
          path: target/nextest/ci/
          retention-days: 1

      - uses: test-summary/action@v2
        if: ${{ !cancelled() }}
        with:
          paths: target/nextest/ci/junit.xml

      # - uses: codecov/codecov-action@v5
      #   if: ${{ !cancelled() }}
      #   with:
      #     files: target/nextest/ci/lcov.info
      #     disable_search: true
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - uses: codecov/test-results-action@v1
        if: ${{ !cancelled() }}
        with:
          file: target/nextest/ci/junit.xml
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate issue body
        if: ${{ !cancelled() }}
        run: |
          # 创建 issue_body.md 并写入标题
          Set-Content -Path issue_body.md -Value "# Lamina 语言测试"

          # 添加带 UTC 时间戳的测试时间
          Add-Content -Path issue_body.md -Value "- 测试时间：$([System.DateTime]::UtcNow.ToString('yyyy-MM-dd HH:mm:ss')) UTC"

          # 添加带链接的版本信息
          Add-Content -Path issue_body.md -Value "- 测试所用版本：[$env:LAMINA_HASH](https://github.com/Lamina-dev/Lamina/commit/$env:LAMINA_HASH)"

          # 解码 Base64 编码的下载地址
          $decodedDownload = [System.Text.Encoding]::UTF8.GetString(
              [System.Convert]::FromBase64String($env:LAMINA_DOWNLOAD)
          )
          Add-Content -Path issue_body.md -Value "- 预编译文件地址：$decodedDownload"

          # 添加日志下载链接
          Add-Content -Path issue_body.md -Value "- 下载测试日志：<${{ steps.upload_artifact.outputs.artifact-url }}>"

          # 添加空行
          Add-Content -Path issue_body.md -Value ""
          Add-Content -Path issue_body.md -Value "---"
          Add-Content -Path issue_body.md -Value ""

          # 追加测试摘要文件
          Get-Content -Path target/nextest/ci/summary.md | Add-Content -Path issue_body.md

      - uses: peter-evans/create-or-update-comment@v4
        if: ${{ !cancelled() }}
        with:
          issue-number: 1
          comment-id: 3192037735
          body-path: issue_body.md
          edit-mode: replace
