name: Test Lamina

on:
  schedule:
    - cron: "30 */8 * * *"
  workflow_dispatch:

permissions:
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --verbose
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
